
package com.buit.his.ws.pack;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PrescriptionService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.3.217:8088/PrescriptionService.asmx?wsdl")
public class PrescriptionService extends Service
{

    private final static URL PRESCRIPTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRESCRIPTIONSERVICE_EXCEPTION;
    private final static QName PRESCRIPTIONSERVICE_QNAME = new QName("http://tempuri.org/", "PrescriptionService");
    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.3.217:8088/PrescriptionService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRESCRIPTIONSERVICE_WSDL_LOCATION = url;
        PRESCRIPTIONSERVICE_EXCEPTION = e;
    }

    public PrescriptionService(String url) {
        super(__getWsdlLocation(url), PRESCRIPTIONSERVICE_QNAME);
    }

    public PrescriptionService(WebServiceFeature... features) {
        super(__getWsdlLocation(null), PRESCRIPTIONSERVICE_QNAME, features);
    }

    public PrescriptionService(URL wsdlLocation) {
        super(wsdlLocation, PRESCRIPTIONSERVICE_QNAME);
    }

    public PrescriptionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRESCRIPTIONSERVICE_QNAME, features);
    }

    public PrescriptionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrescriptionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PrescriptionServiceSoap
     */
    @WebEndpoint(name = "PrescriptionServiceSoap")
    public PrescriptionServiceSoap getPrescriptionServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "PrescriptionServiceSoap"), PrescriptionServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrescriptionServiceSoap
     */
    @WebEndpoint(name = "PrescriptionServiceSoap")
    public PrescriptionServiceSoap getPrescriptionServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "PrescriptionServiceSoap"), PrescriptionServiceSoap.class, features);
    }

    private static URL __getWsdlLocation(String url) {
        if (PRESCRIPTIONSERVICE_EXCEPTION!= null) {
            throw PRESCRIPTIONSERVICE_EXCEPTION;
        }
        URL urlws = null;
        try {
            urlws = new URL(url);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        return urlws;
    }

}
