CREATE TABLE `pack_log`(
  `ID` int NOT NULL AUTO_INCREMENT COMMENT '主键ID' ,
  `JLID` varchar(10) NULL COMMENT 'JLID',
  `STATE` int NULL COMMENT 'STATE',
  `MESSAGE` varchar(1000) NULL COMMENT 'MESSAGE',
  `CREATETIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATETIME',
  PRIMARY KEY (`ID`)
  ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = 'pack_log' ROW_FORMAT = DYNAMIC;